### ISSUE TITLE
Unable to communicate a positive

### ISSUE THREAD

**Issue by xserrat** [RadarCOVID/radar-covid-ios#18]
Using the iPhone 11 Pro with iOS 13.6.1 the app waits for a sms code that never arrives.

**Comment by alrocha** [comment]
Could this be due to your location? In which county _(comunidad autónoma)_ are you located? 
AFAIK the app only works in some of them, the ones that have implemented the "backend" 
Looks like is only available in: Andalucía, Aragón, Baleares, Canarias, Cantabria, Castilla y León, Extremadura y Murcia. 
Madrid and Navarra were added few days ago but not sure if its working already.

**Comment by xserrat** [comment]
I'm from Catalonia so it might be the reason of that... 🤔

**Comment by alrocha** [comment]
I thinks that's the reason, since is not a bug app, or something related to it, I would suggest to close the issue :)

**Comment by xserrat** [comment]
👌🏽  We'll have to wait for the implementation in Catalonia 😄
