### ISSUE TITLE
Why is radar covid NOT participating in test phase for inter operability  for European app????

### ISSUE THREAD

**Issue by ouboub** [RadarCOVID/radar-covid-ios#20]
Hi
I asked this on 
https://github.com/corona-warn-app/cwa-backlog/issues/14#issuecomment-691527556
and that was the answer
**The test phase starts with the country which are able to implement the connection to the EU gateway from their side at this time. Every EU country with an implemented connection can use the the gateway immediately. We have no influence on the implementation of the Spain app.**

so why does radar covid does not implement this connection.
Spain depends very much on tourists, so it is in its own interest
regards
Uwe Brauer

**Comment by jorgej-ramos** [comment]
Apparently, the trial period is planned and scheduled for October, according to the Third Vice President and Minister of Economic Affairs and Digital Transformation, Nadia Calviño.

(Link in Spanish)
https://elpais.com/tecnologia/2020-09-09/espana-probara-en-octubre-la-compatibilidad-de-radar-covid-con-las-apps-de-otros-paises.html

**Comment by ouboub** [comment]
> Apparently, the trial period is planned and scheduled for October, according to the Third Vice President and Minister of Economic Affairs and Digital Transformation, Nadia Calviño.
> 
> (Link in Spanish)
> https://elpais.com/tecnologia/2020-09-09/espana-probara-en-octubre-la-compatibilidad-de-radar-covid-con-las-apps-de-otros-paises.html

but why not earlier, that is almost one month.
are there any technical reasons or is this a political decision?

**Comment by aalmenar** [comment]
From what I see @iCesofT which worked on some of these projects has a repository forked and is making some progress on that: https://github.com/iCesofT/efgs-federation-gateway

**Comment by ouboub** [comment]
> From what I see @iCesofT which worked on some of these projects has a repository forked and is making some progress on that: https://github.com/iCesofT/efgs-federation-gateway

thanks but I am confused, https://github.com/corona-warn-app/cwa-app-ios
is the official repostitory (sponsered by the german government) has 4800 commits of about 70 authors,
this repo just has one commit (sorry to say that) of one author, so what is this repo, not the official one,
what is the repo which is a fork, also not the official one,
so I am confused, I hope nobody will be insulted, but something is odd here, no?

**Comment by aalmenar** [comment]
The repo you are linking is the iOS app for Germany. The repo I linked is the federation gateway on which t-mobile worked and is the one found linked EU site for integration.

**Comment by ouboub** [comment]
> The repo you are linking is the iOS app for Germany. The repo I linked is the federation gateway on which t-mobile worked and is the one found linked EU site for integration.

We have a misunderstanding here. 
1. I sent a link of the official german corona-warn app, that has around 4000 commits. 
2. I found this github repository , which seems to be the one which is devolpping the official radar corona, and it has only ONE commit. I found this odd
3. You pointed out to me another repo, which you said is a fork, but know I understand is the official one that will implement the needed connection to the european apps (it has 48 commits) 
is this correct. do I understand the facts correctly?

**Comment by aalmenar** [comment]
> 
> We have a misunderstanding here.
> 
> 1. I sent a link of the official german corona-warn app, that has around 4000 commits.

Yes, Germany iOS App for Exposure Notifications.

> 2. I found this github repository , which seems to be the one which is devolpping the official radar corona, and it has only ONE commit. I found this odd

Not odd, commit history was not published, just the first commit when they made the source code public. Maybe they should have made the commit history available but it wasn't. This repo, only contains the iOS APP please refer to https://github.com/RadarCovid to see all available projects.

> 3. You pointed out to me another repo, which you said is a fork, but know I understand is the official one that will implement the needed connection to the european apps (it has 48 commits)

The repo i pointed you to is a fork made from the main European Project for integration of European Corona-Warn, Radar-Covid, Swiss Covid etc etc etc apps. and link notifications between all countries. That fork is made by one of the persons that worked on RadarCovid Apps and Servers code.

The main one is located here: https://github.com/eu-federation-gateway-service, which states: "The official European solution for the interoperability between national backend servers of decentralised contact tracing applications to combat COVID-19."

So, this takes time, specially since there are 27 countries, and 1 month is not too much to code a federation service, test with the test servers then integrate with production servers.

**Comment by pantic79** [comment]
Hello,

actually, we are actively participating in test phase, concretely in the second wave. We were focused on Autonomous Communities integration and the schedule for the first wave was very challenging because of that. Once the technical integration with Autonomous Communities is almost finished, we are managing to speed up the interoperability matter.

Thanks.

**Comment by pvieito** [comment]
@pantic79 That's great to hear, is there any approximated timeline?

Also, a more technical related doubt that maybe you or @iCesofT can answer: on the backend API the `/v1/gaen/exposed/` endpoint will continue to only provide TEKs from Spain and only the new [`/v2/gaen/exposed/{country}/{since}` endpoint](https://github.com/DP-3T/dp3t-sdk-backend/pull/237) will expose the cross-country TEKs?

**Comment by pantic79** [comment]
It's scheduled by the end of October but, as I said, we are pushing hard to shorten deadlines. 

Regarding your second question AFAIK the idea is to keep the same endpoint to deliver the TEKs (from Spain and abroad). So, I think your TEK upload analysis project will be valid after that too. :-)

**Comment by pvieito** [comment]
> It's scheduled by the end of October but, as I said, we are pushing hard to shorten deadlines.

Great! 👍🏻

> Regarding your second question AFAIK the idea is to keep the same endpoint to deliver the TEKs (from Spain and abroad). So, I think your TEK upload analysis project will be valid after that too. :-)

Hmm… well in fact that would be a problem for the analysis 😅, as in that case I think we could not analyze the performance of Radar COVID in particular (ie. shared diagnoses per COVID-19 case in Spain) as we could not distinguish Spain's TEKs from other countries's TEKs. The [`TemporaryExposureKeyExport`](https://developers.google.com/android/exposure-notifications/exposure-key-file-format) file inside the ZIP has a `region` field but unfortunately it is applied to the file as a whole not on a per-TEK basis.

**Comment by pantic79** [comment]
Right!. Then let @iCesofT to detail the approach but I think at first it will be just one endpoint because apparently a "One World" approach will be adopted for almost every country (that is, every key is submitted to the EFGS under user consent in order to be distributed to other countries connected to EFGS, and every key from other countries is downloaded from EFGS and delivered to devices with Corona APP installed).

**Comment by iCesofT** [comment]
You are right @pantic79 . We will use the same endpoint so apps don't need to change for now.

Since we are currently working on it and IMHO this is not a issue per se, I would recommend to close the issue

**Comment by pantic79** [comment]
We are already connected to the EFGS from APP 1.1.0 version.

Thanks,
