### ISSUE TITLE
Why is a possible security breach not attented

### ISSUE THREAD

**Issue by ouboub** [RadarCOVID/radar-covid-ios#36]
HI
I am using an iPhone, so that is why I open the issue here:
the issue https://github.com/RadarCOVID/radar-covid-backend-verification-server/issues/6
was closed and reopened but no comment was written no reaction seen, giving that there is security problem
I find this reaction a bit strange to say the least.

Uwe Brauer

**Comment by pantic79** [comment]
It's just because this issue is already solved in the current release published in stores. We are improving the solution for the next release and preparing a public disclosure of this vulnerability in order to clarify an get a better understanding of the situation.
At first, we close the issue because is already solved, but after thinking a bit, we considered more appropiate to keep the issue opened and proceed to close it when the public disclosure is done.

Thanks.
